version: '3.8'

x-monorepo:
  &monorepo
  build:
    args:
      BUILDKIT_INLINE_CACHE:
      NODE_VERSION:
    cache_from:
      - ${IMAGE}
    target: ${BUILD_TARGET}
  image: ${IMAGE}
  working_dir: ${WORKDIR}
  tty: true
  stdin_open: true
  volumes:
    - .:${WORKDIR}

services:
  database:
    image: mongo:5.0.4
    volumes:
      - mongo_data_db:/data/db
    ports:
      - ${MONGO_PORT}:27017
  server:
    << : *monorepo
    command: yarn server
    environment:
      MONGO_URI: mongodb://database:27017/todo
    ports:
      - ${SERVER_PORT}:3000
      - ${SERVER_DEBUG_PORT}:9320
  client:
    << : *monorepo
    command: yarn client
    ports:
      - ${CLIENT_PORT}:3000

volumes:
  mongo_data_db:
